/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        bg:     { primary: 'var(--color-bg-primary)', secondary: 'var(--color-bg-secondary)', elevated: 'var(--color-bg-elevated)', input: 'var(--color-bg-input)' },
        tx:     { primary: 'var(--color-text-primary)', secondary: 'var(--color-text-secondary)', tertiary: 'var(--color-text-tertiary)', inverse: 'var(--color-text-inverse)' },
        brand:  { DEFAULT: 'var(--color-brand-primary)', primary: 'var(--color-brand-primary)', secondary: 'var(--color-brand-secondary)', accent: 'var(--color-brand-accent)', glow: 'var(--color-brand-glow)' },
        status: { success: 'var(--color-status-success)', error: 'var(--color-status-error)', warning: 'var(--color-status-warning)', info: 'var(--color-status-info)' },
        line:   { DEFAULT: 'var(--color-border-default)', strong: 'var(--color-border-strong)', brand: 'var(--color-border-brand)' },
        // Material Design System Colors
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#d7e3fa",
        "tertiary": "#0b1728",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#b5c8e4",
        "on-secondary-container": "#4a6774",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#8194ae",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed": "#101c2c",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-secondary-fixed-variant": "#2e4b57",
        "tertiary-fixed-dim": "#bbc7dd",
        "tertiary-container": "#202c3d",
        "surface-container-lowest": "#ffffff",
        "secondary": "#466270",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001f2a",
        "secondary-fixed-dim": "#adcbda",
        "secondary-container": "#c6e4f4",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "primary-container": "#1a2c42",
        "on-primary-fixed-variant": "#36485f",
        "error-container": "#ffdad6",
        "outline-variant": "#c2c7ca",
        "surface-variant": "#e1e3e4",
        "surface": "#f8f9fa",
        "secondary-fixed": "#c9e7f7",
        "surface-container": "#edeeef",
        "on-background": "#191c1d",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#8793a8",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#42484a",
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "outline": "#73787a",
        "primary": "#03182d",
        "inverse-primary": "#b5c8e4",
        "surface-container-high": "#e7e8e9",
        "surface-tint": "#4e6078",
        "on-primary-fixed": "#081c32",
        "surface-container-highest": "#e1e3e4"
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Inter', 'sans-serif'],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        'card':    '0 1px 3px rgba(0,0,0,.08), 0 1px 2px rgba(0,0,0,.06)',
        'card-lg': '0 4px 12px rgba(0,0,0,.1)',
        'glow':    '0 0 20px var(--color-brand-glow)',
        'glow-lg': '0 0 30px var(--color-brand-glow), 0 4px 20px rgba(0,0,0,.12)',
      },
      borderRadius: {
        'xl':  '12px',
        '2xl': '16px',
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
